import { Contract } from "../types/contract";

export const contracts: Contract[] = [
    {
      "id": "V0001",
      "title": "SLA Bank Kernsystem",
      "status": "Abgelehnt",
      "type": "Dienstleistungsvertrag",
      "partner": "",
      "responsibility": "Max Bauer",
      "startDate": "12.11.2017",
      "endDate": "12.11.2022",
      "lastModification": "01.09.2022 10:43"
    },
    {
      "id": "V0003",
      "title": "Geschäftsauto Leasingvertrag",
      "status": "Aktiv",
      "type": "Leasingvertrag",
      "partner": "",
      "responsibility": "Hans Muster",
      "startDate": "25.08.2017",
      "endDate": "25.08.2021",
      "lastModification": "02.02.2022 14:40"
    },
    {
      "id": "V0004",
      "title": "Immobilienverwaltung Stadthof Sursee",
      "status": "Prüfung",
      "type": "Kaufvertrag",
      "partner": "Cloud Provider: Turle Cloud",
      "responsibility": "Petra Ivanov",
      "startDate": "11.03.2020",
      "endDate": "05.12.2020",
      "lastModification": "30.11.2020 09:25"
    },
    {
      "id": "V0006",
      "title": "Rahmenvertrag Bank - Kernsystem",
      "status": "Aktiv",
      "type": "Dienstleistungsvertrag",
      "partner": "Firma XYZ; Cloud Provider: Turle Cloud",
      "responsibility": "John Heart",
      "startDate": "01.01.2016",
      "endDate": "31.12.2020",
      "lastModification": "29.09.2022 10:54"
    },
    {
      "id": "V0007",
      "title": "Rahmenvertrag Bank - Kernsystem",
      "status": "Aktiv",
      "type": "Kaufvertrag",
      "partner": "",
      "responsibility": "Samantha Bright",
      "startDate": "01.01.2019",
      "endDate": "31.12.2023",
      "lastModification": "03.06.2021 06:47"
    },
    {
      "id": "V0008",
      "title": "Finnova Usage Fee",
      "status": "Aktiv",
      "type": "Dienstleistungsvertrag",
      "partner": "",
      "responsibility": "Samantha Bright",
      "startDate": "01.04.2011",
      "endDate": "22.10.2025",
      "lastModification": "03.05.2021 00:05"
    },
    {
      "id": "V0009",
      "title": "Marktstudie Vertragsmanagement",
      "status": "Abgelehnt",
      "type": "Projektvertrag",
      "partner": "",
      "responsibility": "Hans Muster",
      "startDate": "26.05.2020",
      "endDate": "29.10.2020",
      "lastModification": "14.10.2020 14:07"
    },
    {
      "id": "V0010",
      "title": "Test Rahmenvertrag",
      "status": "Prüfung",
      "type": "Rahmenvertrag",
      "partner": "",
      "responsibility": "Max Bauer",
      "startDate": "26.01.2020",
      "endDate": "26.01.2021",
      "lastModification": "08.02.2022 13:15"
    },
    {
      "id": "V0011",
      "title": "Vetrag (Kosten)",
      "status": "Entwurf",
      "type": "",
      "partner": "",
      "responsibility": "",
      "startDate": "",
      "endDate": "",
      "lastModification": "09.02.2022 15:02"
    },
    {
      "id": "V0012",
      "title": "Darlehen 2020121501-20251215",
      "status": "Aktiv",
      "type": "Darlehensvertrag",
      "partner": "Urner Kantonalbank",
      "responsibility": "Kanton Uri",
      "startDate": "15.12.2020",
      "endDate": "15.04.2021",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0013",
      "title": "Mietvertrag Garagen und Abstellplätze",
      "status": "Aktiv",
      "type": "Mietvertrag",
      "partner": "",
      "responsibility": "",
      "startDate": "03.02.2021",
      "endDate": "",
      "lastModification": "03.02.2021 17:23"
    },
    {
      "id": "V0014",
      "title": "Alarmempfangsabonnement",
      "status": "Aktiv",
      "type": "Dienstleistungsvertrag",
      "partner": "Securitas",
      "responsibility": "Hans Muster",
      "startDate": "01.12.2020",
      "endDate": "",
      "lastModification": "03.02.2021 17:59"
    },
    {
      "id": "V0015",
      "title": "Instandhaltung Brandmeldeanlage Taubenstr.",
      "status": "Aktiv",
      "type": "Wartungsvertrag",
      "partner": "Securitas",
      "responsibility": "Hans Muster",
      "startDate": "04.02.2021",
      "endDate": "",
      "lastModification": "04.02.2021 09:58"
    },
    {
      "id": "V0016",
      "title": "Drucker Erneuerung",
      "status": "Aktiv",
      "type": "",
      "partner": "",
      "responsibility": "",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:58"
    },
    {
      "id": "V0017",
      "title": "GRC Toolbox",
      "status": "Aktiv",
      "type": "Lizenzvertrag",
      "partner": "Swiss GRC AG",
      "responsibility": "Max Bauer",
      "startDate": "30.09.2020",
      "endDate": "",
      "lastModification": "31.03.2021 11:55"
    },
    {
      "id": "V0018",
      "title": "Servicevertrag für Aufzugsanlagen",
      "status": "Aktiv",
      "type": "",
      "partner": "",
      "responsibility": "",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:58"
    },
    {
      "id": "V0019",
      "title": "Stromliefervertrag",
      "status": "Aktiv",
      "type": "Dienstleistungsvertrag",
      "partner": "Kantonale Stadtwerke AG",
      "responsibility": "Petra Ivanov",
      "startDate": "01.01.2021",
      "endDate": "05.05.2022",
      "lastModification": "04.02.2021 09:58"
    },
    {
      "id": "V0020",
      "title": "Wärmelieferungsvertrag",
      "status": "Aktiv",
      "type": "Dienstleistungsvertrag",
      "partner": "Wärme AG Luzern",
      "responsibility": "",
      "startDate": "01.01.2021",
      "endDate": "",
      "lastModification": "04.02.2021 09:58"
    },
    {
      "id": "V0021",
      "title": "Unternehmungslizenzvertrag Citrix",
      "status": "Entwurf",
      "type": "",
      "partner": "",
      "responsibility": "",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:58"
    },
    {
      "id": "V0022",
      "title": "Wartungsvertrag Rauch- und Wärmeabzugsanlage",
      "status": "Abgelehnt",
      "type": "Wartungsvertrag",
      "partner": "Securitas",
      "responsibility": "",
      "startDate": "02.11.2020",
      "endDate": "",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0024",
      "title": "Wartungsvertrag Klima",
      "status": "Entwurf",
      "type": "",
      "partner": "Kantonale Stadtwerke AG",
      "responsibility": "Petra Ivanov",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0025",
      "title": "Stromrückliefervertrag für erneuerbare Energien",
      "status": "Prüfung",
      "type": "Werkvertrag",
      "partner": "Kantonale Stadtwerke AG",
      "responsibility": "Petra Ivanov",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0026",
      "title": "Service Vereinbarung ERU",
      "status": "Entwurf",
      "type": "",
      "partner": "",
      "responsibility": "",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0027",
      "title": "Glasfasererschliessung",
      "status": "Aktiv",
      "type": "Dienstleistungsvertrag",
      "partner": "Telekomunikationsgeselschaft",
      "responsibility": "Petra Ivanov",
      "startDate": "01.01.2021",
      "endDate": "05.05.2022",
      "lastModification": "04.02.2021 07:50"
    },
    {
      "id": "V0028",
      "title": "Geheimhaltungsvereinbarung",
      "status": "Aktiv",
      "type": "Kooperationsvertrag",
      "partner": "Urner Kantonalbank",
      "responsibility": "Max Bauer",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0029",
      "title": "AGB für Radio- und TV-Sponsoring",
      "status": "Entwurf",
      "type": "Rahmenvertrag",
      "partner": "Telekomunikationsgeselschaft",
      "responsibility": "Petra Ivanov",
      "startDate": "",
      "endDate": "",
      "lastModification": "03.02.2021 17:49"
    },
    {
      "id": "V0030",
      "title": "AH 1 Leistungsbeschreibung",
      "status": "Entwurf",
      "type": "",
      "partner": "",
      "responsibility": "",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0031",
      "title": "Aktienkaufvertrag",
      "status": "Aktiv",
      "type": "Finanzvertrag",
      "partner": "Börse NY",
      "responsibility": "Petra Ivanov",
      "startDate": "01.02.2021",
      "endDate": "15.04.2021",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0032",
      "title": "PSP Agreement",
      "status": "Aktiv",
      "type": "",
      "partner": "",
      "responsibility": "",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0033",
      "title": "Shareholder Agreement",
      "status": "Aktiv",
      "type": "Auftragsverarbeitungsvertrag",
      "partner": "",
      "responsibility": "Max Bauer",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0034",
      "title": "Handyzahlungen MobileTech",
      "status": "Prüfung",
      "type": "Kaufvertrag",
      "partner": "Telekomunikationsgeselschaft",
      "responsibility": "Max Bauer",
      "startDate": "01.01.2021",
      "endDate": "05.05.2022",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0035",
      "title": "FMIA Agreement",
      "status": "Aktiv",
      "type": "",
      "partner": "",
      "responsibility": "",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0036",
      "title": "Unterhaltungssoftware-Produkt NHL 15",
      "status": "Aktiv",
      "type": "",
      "partner": "",
      "responsibility": "",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0037",
      "title": "Offerte MoneyFit Betrieb 2016",
      "status": "Aktiv",
      "type": "Projektvertrag",
      "partner": "MoneyFit",
      "responsibility": "Max Bauer",
      "startDate": "01.01.2020",
      "endDate": "01.01.2021",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0038",
      "title": "Confidentiality Agreement Apple Inc.",
      "status": "Prüfung",
      "type": "",
      "partner": "",
      "responsibility": "",
      "startDate": "",
      "endDate": "",
      "lastModification": "04.02.2021 09:59"
    },
    {
      "id": "V0039",
      "title": "PA Test Vertrag",
      "status": "Aktiv",
      "type": "",
      "partner": "",
      "responsibility": "Dreni Drenica",
      "startDate": "",
      "endDate": "",
      "lastModification": "10.12.2021 00:05"
    },
    {
      "id": "V0040",
      "title": "myCoolContract",
      "status": "Aktiv",
      "type": "Dienstleistungsvertrag",
      "partner": "Partnerfirma ACME Inc.",
      "responsibility": "",
      "startDate": "01.04.2019",
      "endDate": "",
      "lastModification": "25.10.2021 13:11"
    },
    {
      "id": "V0041",
      "title": "Vereinbarung zur Auftragsdatenverarbeitung",
      "status": "Aktiv",
      "type": "Auftragsverarbeitungsvertrag",
      "partner": "Swiss GRC AG",
      "responsibility": "Petra Ivanov",
      "startDate": "",
      "endDate": "",
      "lastModification": "13.11.2021 11:25"
    },
    {
      "id": "V0042",
      "title": "Test Vertrag",
      "status": "Entwurf",
      "type": "Leasingvertrag",
      "partner": "Swiss GRC AG; Partnerfirma ACME Inc.",
      "responsibility": "",
      "startDate": "25.04.2022",
      "endDate": "",
      "lastModification": "25.04.2022 19:03"
    },
    {
      "id": "V0043",
      "title": "Vertrag 2",
      "status": "Entwurf",
      "type": "",
      "partner": "Firma XYZ",
      "responsibility": "",
      "startDate": "",
      "endDate": "",
      "lastModification": "28.04.2022 13:50"
    },
    {
      "id": "V0044",
      "title": "Testvertrag Finanzamt",
      "status": "Entwurf",
      "type": "",
      "partner": "",
      "responsibility": "",
      "startDate": "",
      "endDate": "",
      "lastModification": "28.04.2022 13:59"
    },
    {
      "id": "V0045",
      "title": "Service Level Agreement",
      "status": "Entwurf",
      "type": "Dienstleistungsvertrag",
      "partner": "Sparke Universe AG",
      "responsibility": "",
      "startDate": "01.06.2022",
      "endDate": "",
      "lastModification": "24.05.2022 18:39"
    },
    {
      "id": "V0046",
      "title": "Mietvertrag Mermaid Lagoon",
      "status": "Prüfung",
      "type": "Mietvertrag",
      "partner": "Sparke Universe AG",
      "responsibility": "Hans Muster",
      "startDate": "01.07.2022",
      "endDate": "",
      "lastModification": "24.05.2022 18:49"
    },
    {
      "id": "V0047",
      "title": "Service Level Agreement",
      "status": "Aktiv",
      "type": "Lizenzvertrag",
      "partner": "Sparke Universe AG",
      "responsibility": "Hans Muster",
      "startDate": "",
      "endDate": "",
      "lastModification": "24.05.2022 18:58"
    },
    {
      "id": "V0049",
      "title": "Mietvertrag: Lagerraum LU",
      "status": "Aktiv",
      "type": "Mietvertrag",
      "partner": "Swiss GRC AG; Cloud Provider: Turle Cloud",
      "responsibility": "Samantha Bright",
      "startDate": "01.10.2022",
      "endDate": "01.01.2024",
      "lastModification": "19.09.2022 13:19"
    }
  ]
  